name: Deploy Feature Branch to GitHub Pages

on:
  push:
    branches:
      - new_theam

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd portfolio-website && npm install

      - name: Build project
        run: cd portfolio-website && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: portfolio-website/build
          cname: feature.akhila6423.com
